### PR TITLE
Refactor CustomButton and Make StandardText matches Figma

### PR DESCRIPTION
**Pull request by sukritsangvong**
Changelist:
- Refactor `CustomButton`
  - Remove `isSmall`, `isBig`, ... 
  - `CustomButton` now takes optional minHeight and minHorizontalMargin
  - All `CustomButton` with one-line text all have the same size and will expand based on the lines of the text
- Copy text style from ParentGuide and applied it to `StandardText`
- Add `Constant.js` file to keep track of the sizes of `CustomButton`
- Add Icon to button right of `CustomButton` on the Play page (Need pink PNG for 'my bright future'

image
image
image
image

### CODE REVIEW

**Review by RichartE — CHANGES_REQUESTED** [review]
These changes mess up the formatting for the parent guide text boxes.

**Comment by sukritsangvong** [comment]
@RichartE We talked in the meeting last time that we wanted to make the button the same width as the other pages' to avoid the empty space concern that @varmaa23 was talking about. I can change it back, but I believe this is what it is supposed to be. @varmaa23 pls correct me if I'm wrong.

**Comment by dazedcodes** [comment]
These changes look good. I have no objections.

**Comment by varmaa23** [comment]
Yes that’s right

**Comment by sukritsangvong** [comment]
If u guys think everything is good, pls approve the PR! @RichartE @dazedcodes @varmaa23

**Review by varmaa23 — APPROVED** [review]

**Review by mayawhocodes — APPROVED** [review]
These changes help make all of the buttons look consistent across the app and increase the brevity of the code. 

I'm looking forward to using some of the strategies implemented here to help make the home screen responsive and look consistent across different phone sizes. Nice job!

**Review by RichartE — APPROVED** [review]

**Pull request merged**
